name: Infostat
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  Update:
    runs-on: ubuntu-latest 
    permissions:
        contents: write
    steps:

      - uses: bayselonarrend/infometrics-articles@1.1
        with:
          profile-id: '1793672'
          count: '3'
          template: ./article2.html
