name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: product
    permissions:
      contents: write
    steps:
    - name: General
      if: ${{ success() || failure() }}
      uses: lowlighter/metrics@latest
      with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
                  # Options
          template: classic
          base: header, repositories, metadata
          config_timezone: Europe/Moscow
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

    - name: Repos
      if: ${{ success() || failure() }}
      uses: lowlighter/metrics@latest
      with:
        filename: repos.svg
        token: ${{ secrets.METRICS_TOKEN }}
                  # Options  
        base: ""
        plugin_repositories: yes
        plugin_repositories_featured: bayselonarrend/OpenIntegrations, bayselonarrend/1Charts, bayselonarrend/2athenaeum
        plugin_repositories_order: starred, random

    - name: Recent posts with descriptions and cover images
      if: ${{ success() || failure() }}
      uses: lowlighter/metrics@latest
      with:
          filename: posts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugin_posts_limit: 2
          plugin_posts_descriptions: yes
          plugin_posts_covers: yes

    - name: Map
      if: ${{ success() || failure() }}
      uses: lowlighter/metrics@latest
      with:
        filename: map.svg
        token: ${{ secrets.METRICS_TOKEN }}
                  # Options  
        base: ""
        plugin_isocalendar: yes
        plugin_isocalendar_duration: full-year
